// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Value;

import com.ctre.phoenix6.controls.NeutralOut;
import com.ctre.phoenix6.controls.PositionTorqueCurrentFOC;
import com.ctre.phoenix6.controls.PositionVoltage;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix6.hardware.TalonFX;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants; 
import frc.robot.RobotContainer;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Hopper extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private TalonFX fuelGrabber;
    private DoubleSolenoid  hopperLeftSolenoid;
    private DoubleSolenoid  hopperRightSolenoid;

    private DigitalInput hopperExtendSwitch;
    private DigitalInput hopperRetractSwitch;
    public XboxController m_joystick = new XboxController(0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    TalonFX m_fx = new TalonFX(15, "rio");
    /* Be able to switch which control request to use based on a button press */
    /* Start at position 0, use slot 0 */

    final PositionVoltage m_positionVoltage = new PositionVoltage(0).withSlot(0);
    /* Start at position 0, use slot 1 */
    final PositionTorqueCurrentFOC m_positionTorque = new PositionTorqueCurrentFOC(0).withSlot(1);
    /* Keep a brake request so we can disable the motor */
    final NeutralOut m_brake = new NeutralOut();

    /**
    *
    */
    public Hopper() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        fuelGrabber = new TalonFX(14, "rio");

        hopperLeftSolenoid = new DoubleSolenoid(20, PneumaticsModuleType.REVPH, 4,5);
//        hopperRightSolenoid = new DoubleSolenoid(5, PneumaticsModuleType.REVPH, 12,13);
        hopperExtendSwitch = new DigitalInput(0);
        addChild("hopperExtendSwitch", hopperExtendSwitch);

        hopperRetractSwitch = new DigitalInput(1);
        addChild("hopperRetractSwitch", hopperRetractSwitch);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        hopperLeftSolenoid.set(DoubleSolenoid.Value.kReverse);
//        hopperRightSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
/*        TalonFXConfiguration configs = new TalonFXConfiguration();
        configs.Slot0.kP = 2.4; // An error of 1 rotation results in 2.4 V output
        configs.Slot0.kI = 0; // No output for integrated error
        configs.Slot0.kD = 0.1; // A velocity of 1 rps results in 0.1 V output
        // Peak output of 8 V
        configs.Voltage.withPeakForwardVoltage(Volts.of(8))
                .withPeakReverseVoltage(Volts.of(-8));
        CurrentLimitsConfigs fxCurrent = configs.CurrentLimits;
        fxCurrent.StatorCurrentLimit = 5;

        configs.Slot1.kP = 60; // An error of 1 rotation results in 60 A output
        configs.Slot1.kI = 0; // No output for integrated error
        configs.Slot1.kD = 6; // A velocity of 1 rps results in 6 A output
        // Peak output of 120 A
        configs.TorqueCurrent.withPeakForwardTorqueCurrent(Amps.of(120))
                .withPeakReverseTorqueCurrent(Amps.of(-120)); */
        /* Retry config apply up to 5 times, report if failure */
/*        StatusCode status = StatusCode.StatusCodeNotInitialized;
        for (int i = 0; i < 5; ++i) {
            status = m_fx.getConfigurator().apply(configs);
            if (status.isOK())
                break;
        }
        if (!status.isOK()) {
            System.out.println("Could not apply configs, error code: " + status.toString());
        }
*/
        /* Make sure we start at 0 */
/*        m_fx.setPosition(0);
    }
*/
    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putBoolean("Hopper Extended", isHopperExtended());
        SmartDashboard.putBoolean("Hopper Retracted", isHopperRetracted());
        SmartDashboard.putNumber("position", m_fx.getPosition().getValueAsDouble());
/*      double desiredRotations = m_joystick.getLeftY() * 10; // Go for plus/minus 10 rotations
        if (Math.abs(desiredRotations) <= 0.1) { // Joystick deadzone
            desiredRotations = 0;
        }
        desiredRotations = 2;

        if (m_joystick.getLeftBumperButton()) {
             Use position voltage 
            m_fx.setControl(m_positionVoltage.withPosition(desiredRotations));
            SmartDashboard.putBoolean("buttonPressed", true);
        } else if (m_joystick.getRightBumperButton()) {
            /* Use position torque 
            m_fx.setControl(m_positionTorque.withPosition(desiredRotations));
        } else {
            SmartDashboard.putBoolean("buttonPressed", false);
            /* Disable the motor instead 
            m_fx.setControl(m_brake);
        }

        if (isHopperRetracted()) {
            m_fx.setPosition(0);
        }
*/
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void setFuelGrabberSpeed() {
        fuelGrabber.set(0.1);

    }

    public void stopFuelGrabber() {
        fuelGrabber.set(0);

    }

    public void ifJammed() {
        fuelGrabber.set(-0.1);

    }

    public void setHopperExtend() {
        if (RobotContainer.getInstance().ph.getPressure(0) >= 45){
            hopperLeftSolenoid.set(DoubleSolenoid.Value.kForward);
//          hopperRightSolenoid.set(DoubleSolenoid.Value.kForward);
        }

    }

    public void setHopperRetract() {
        hopperLeftSolenoid.set(DoubleSolenoid.Value.kReverse);
//        hopperRightSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    

    public boolean isHopperExtended() {
        return hopperExtendSwitch.get();
    }

    public boolean isHopperRetracted() {
        return hopperRetractSwitch.get();
    }

}