// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import com.ctre.phoenix6.controls.NeutralOut;
import com.ctre.phoenix6.controls.PositionTorqueCurrentFOC;
import com.ctre.phoenix6.controls.PositionVoltage;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkMax;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import frc.robot.Robot;
import frc.robot.RobotContainer;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Hopper extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMax leftFuelGrabber;
    private SparkMax rightFuelGrabber;
    private DoubleSolenoid  hopperLeftSolenoid;
    private DoubleSolenoid  hopperRightSolenoid;
    // private ArmoredCoreAC v4Rusty;

    private DigitalInput hopperExtendSwitch;
    private DigitalInput hopperRetractSwitch;
    private SparkMax hopperFloorTransferSecure;
    public XboxController m_joystick = new XboxController(0);
    public boolean isExtending;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // TalonFX m_fx = new TalonFX(15, "rio");
    /* Be able to switch which control request to use based on a button press */
    /* Start at position 0, use slot 0 */

    final PositionVoltage m_positionVoltage = new PositionVoltage(0).withSlot(0);
    /* Start at position 0, use slot 1 */
    final PositionTorqueCurrentFOC m_positionTorque = new PositionTorqueCurrentFOC(0).withSlot(1);
    /* Keep a brake request so we can disable the motor */
    final NeutralOut m_brake = new NeutralOut();

    /**
    *
    */
    public Hopper() {
        leftFuelGrabber = new SparkMax(16, MotorType.kBrushless);
        rightFuelGrabber = new SparkMax(15, MotorType.kBrushless);
        hopperFloorTransferSecure = new SparkMax(18, MotorType.kBrushless);
        

        hopperLeftSolenoid = new DoubleSolenoid(20, PneumaticsModuleType.REVPH,12,11);
        //hopperRightSolenoid = new DoubleSolenoid(20, PneumaticsModuleType.REVPH,14,15);
        hopperExtendSwitch = new DigitalInput(0);
        addChild("hopperExtendSwitch", hopperExtendSwitch);

        hopperRetractSwitch = new DigitalInput(1);
        addChild("hopperRetractSwitch", hopperRetractSwitch);
//        hopperRightSolenoid.set(DoubleSolenoid.Value.kReverse);

        isExtending = false;

        hopperLeftSolenoid.set(DoubleSolenoid.Value.kReverse);
        //hopperRightSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putBoolean("Hopper Extended", isHopperExtended());
        SmartDashboard.putBoolean("Hopper Retracted", isHopperRetracted());
        SmartDashboard.putNumber("Hopper Floor Transfer Speed", hopperFloorTransferSecure.get());
                // SmartDashboard.putNumber("position", m_fx.getPosition().getValueAsDouble());
/*      double desiredRotations = m_joystick.getLeftY() * 10; // Go for plus/minus 10 rotations
        if (Math.abs(desiredRotations) <= 0.1) { // Joystick deadzone
            desiredRotations = 0;
        }
        desiredRotations = 2;

        if (m_joystick.getLeftBumperButton()) {
             Use position voltage 
            m_fx.setControl(m_positionVoltage.withPosition(desiredRotations));
            SmartDashboard.putBoolean("buttonPressed", true);
        } else if (m_joystick.getRightBumperButton()) {
            /* Use position torque 
            m_fx.setControl(m_positionTorque.withPosition(desiredRotations));
        } else {
            SmartDashboard.putBoolean("buttonPressed", false);
            /* Disable the motor instead 
            m_fx.setControl(m_brake);
        }

        if (isHopperRetracted()) {
            m_fx.setPosition(0);
        }
*/
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void setFuelGrabberSpeed() {
        leftFuelGrabber.set(0.1);
        rightFuelGrabber.set(0.1);

    }

    public void stopFuelGrabber() {
        leftFuelGrabber.set(0);
        rightFuelGrabber.set(0);

    }
    public void setHopperFloorTransferSecureSpeed(double speed) {
        hopperFloorTransferSecure.set(speed);

    }   
    public void stopHopperFloorTransferSecure() {
        hopperFloorTransferSecure.set(0);

    }
    public void ifIntakeJammed() {
        leftFuelGrabber.set(-0.1);
        rightFuelGrabber.set(-0.1);

    }
    public void clearIntakeJam() {
        leftFuelGrabber.set(0);
        rightFuelGrabber.set(0);

    }
    public void ifHopperFloorTransferSecureIsBlocked() {
         hopperFloorTransferSecure.set(-0.1);

    }
    public void clearHopperFloorTransferSecureBlockage() {
        hopperFloorTransferSecure.set(0);

    }
    public void setHopperExtend() {
         //if (Robot.getInstance().m_climb.currentLockdownMode == LockdownMode.full || Robot.getInstance().m_climb.currentLockdownMode == LockdownMode.partial) {
            
         //}
         //else{
             isExtending = true;
          //    if (Robot.getInstance().ph.getPressure(0) >= 45){
                hopperLeftSolenoid.set(DoubleSolenoid.Value.kForward);
                //hopperRightSolenoid.set(DoubleSolenoid.Value.kForward);
                System.out.println("Extending");
          //    }
         //}

    }

    public void setHopperRetract() {
        isExtending = false;
        hopperLeftSolenoid.set(DoubleSolenoid.Value.kReverse);
        //hopperRightSolenoid.set(DoubleSolenoid.Value.kReverse);
        System.out.println("Retracting");
    }
    
    public void retractingHopperForLockdown() {
        isExtending = false;
        hopperLeftSolenoid.set(DoubleSolenoid.Value.kReverse);
        //hopperRightSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    public boolean isHopperExtended() {
        return !hopperExtendSwitch.get();
    }

    public boolean isHopperRetracted() {
        return !hopperRetractSwitch.get();
    }

    public boolean isExtending() {
        return isExtending;
    }

}