// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix6.hardware.TalonFX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Hopper extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private TalonFX fuelGrabber;
private TalonFX hopperMotor1;
private TalonFX hopperMotor2;

private DigitalInput hopperExtendSwitch;
private DigitalInput hopperRetractSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Hopper() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
fuelGrabber = new TalonFX(0, "rio");
 
 

hopperMotor1 = new TalonFX(1, "rio");
 
 

hopperMotor2 = new TalonFX(2, "rio");
 
        hopperExtendSwitch = new DigitalInput(0);
        addChild("hopperExtendSwitch", hopperExtendSwitch);

        hopperRetractSwitch = new DigitalInput(1);
        addChild("hopperRetractSwitch", hopperRetractSwitch);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putBoolean("Hopper Extended", isHopperExtended());
        SmartDashboard.putBoolean("Hopper Retracted", isHopperRetracted());
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void setFuelGrabberSpeed() {
        fuelGrabber.set(0.1);

    }
    public void stopFuelGrabber() {
        fuelGrabber.set(0);

    }

    public void ifJammed() {
        fuelGrabber.set(-0.1);

    }

    public void setHopperExtend() {
        hopperMotor1.set(0.1);
        hopperMotor2.set(0.1);
        
    }
    
    public void setHopperRetract() {
        hopperMotor1.set(-0.1);
        hopperMotor2.set(-0.1);
    }
    public void stopHopper() {
        hopperMotor1.set(0);
        hopperMotor2.set(0);
    }

    public boolean isHopperExtended() {
        return hopperExtendSwitch.get();    
    }
    public boolean isHopperRetracted() {
        return hopperRetractSwitch.get();    
    }
}

        



